platform:ios, '8.0'
target '工具' do
inhibit_all_warnings!

pod "AFNetworking", "~> 3.2.0"
pod "YYCache", "~> 1.0.4"
pod "CYLTabBarController", "~> 1.17.6"
pod "FDFullscreenPopGesture", "~> 1.1"
pod "MBProgressHUD", "~> 1.1.0"
pod "FMDB", "~> 2.7.2"
pod "MJExtension", "~> 3.0.13"
pod "Masonry", "~> 1.1.0"
pod "SDWebImage", "~> 4.3.0"
pod "MJRefresh", "~> 3.1.15.3"
pod "TZImagePickerController", "~> 2.0.0.6"
end
